spring.application.name=job0111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/yiludbcopy
spring.datasource.username=root
spring.datasource.password=13730708827/lyj

# ??????????
spring.web.error.include-stacktrace=always
spring.web.error.include-message=always

# ??SQL????????
logging.level.com.lyj.job0111.dao=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG